### ISSUE TITLE
训练集和测试集拆分问题

### ISSUE THREAD

**Issue by iseesaw** [lxchtan/HeterMPC#1]
您好，请问这个仓库中使用的 ijcai2019 的数据集，和 [MPC-BERT](https://github.com/JasonForJoy/MPC-BERT) 中的使用的训练集和测试集拆分是不是不一样呀？盼复，谢谢~

**Comment by JasonForJoy** [comment]
@iseesaw 
感谢你对我们工作的关注。

首先，我们通过GSN原作者那里得到的处理脚本帮我们获取了没有切分（train+valid+test）总共321, 725个对话样例，我们根据GSN论文中的描述，随机采样5, 000当做valid和5, 000当做test。因此该过程存在采样随机性。

HeterMPC中的数据集包含了额外的```relation_user```标签，该标签信息在原先的GSN模型中用到，尽管最终HeterMPC中没有用到因该标签信息，但我们仍对其进行了保留，方便后续研究人员使用该信息。该标签信息的具体含义，可参见GSN源repo：https://github.com/morning-dews/GSN-Dialogues

MPC-BERT中因为没有建模图结构信息，因此去除了```relation_user```标签，并又随机采样了一次。因此，在细节上（train+valid+test）会有所不同，但两者都是从同源同分布的数据进行了随机采样。

**Comment by iseesaw** [comment]
哦哦，明白啦！感谢回复~
