### ISSUE TITLE
Can you provide the script to evaluate the results?

### ISSUE THREAD

**Issue by ghost** [lxchtan/HeterMPC#2]
Hello, thanks for your nice work.
I am current working on this topic, too, and I tried to evaluate the two files you provided (`HeterBERT.txt` and `HeterBART.txt`) under the path `/results/Papaer/` using the Metric Classes in file `/utils/metrics.py` with the evaluation script written by myself. However, I get very low scores as:
```
HeterBERT:
{'Rouge-L': 7.698622682672128, 'BLEU-1': 9.045871176830515, 'BLEU-2': 1.626240916390646, 'BLEU-3': 0.481828304508101, 'BLEU-4': 0.23206281088366149}
HeterBART:
{'Rouge-L': 7.496931635346263, 'BLEU-1': 9.339382529435177, 'BLEU-2': 1.9110335546170056, 'BLEU-3': 0.5608368753366778, 'BLEU-4': 0.30480215340240163}
```
I am wondering if it is because my evaluation script misses something that you use in yours. Can you kindly provided a script that can report scores from some `predictions.txt` and a `references.txt`, whose format is just like your provided `HeterBERT.txt`? Thank you very much in advance.

Here is the core part of my evaluation script:

```
from utils.metrics import ROUGE, BLEU, METEOR

# pred_responses, golden_responses = just_read_the_text_from_files

rf = ROUGE()
b1, b2, b3, b4 = BLEU(n=1), BLEU(n=2), BLEU(n=3), BLEU(n=4)
meteor = METEOR()

for pred, ans in zip(pred_responses, golden_responses):
    rf.update((pred, ans))
    b1.update((pred, ans))
    b2.update((pred, ans))
    b3.update((pred, ans))
    b4.update((pred, ans))
    meteor.update((pred, ans))

result_dict = {"Rouge-L": rf.compute()*100, "BLEU-1": b1.compute()*100,\
        "BLEU-2": b2.compute()*100, "BLEU-3": b3.compute()*100, "BLEU-4": b4.compute()*100}
print(result_dict)
```

**Comment by lxchtan** [comment]
Thank you for your interest in our work.
I apologize for not putting the evaluation script on github before. In fact, we used the same evaluation script "coco-caption" as in previous work.
I have now updated the evaluation code to that repo, and updated the README accordingly.
If you have any other questions, feel free to ask.

**Comment by ghost** [comment]
Thank you for your quick reply. I am now able to get the same scores as those in the paper.
