### ISSUE TITLE
The vocab size of nn.Embedding here seems should be 4, ie. nn.Embedding(4,  config.d_model)

### ISSUE THREAD

**Issue by thdai2000** [lxchtan/HeterMPC#3]
The vocab size of nn.Embedding here seems should be 4, ie. nn.Embedding(4,  config.d_model):
https://github.com/lxchtan/HeterMPC/blob/c9bdc6a14978a0679b9305b97de53cc39192f2e9/models/heterbart.py#L32
otherwise error will occur at:
https://github.com/lxchtan/HeterMPC/blob/c9bdc6a14978a0679b9305b97de53cc39192f2e9/models/heterbart.py#L107

**Comment by lxchtan** [comment]
Thank you for your interest in our work.
In the calculation of `ans_total`, `decoder_ans_idxs` and `decoder_ans_from` are not equal.
https://github.com/lxchtan/HeterMPC/blob/c9bdc6a14978a0679b9305b97de53cc39192f2e9/models/heterbart.py#L106

Thus the result of `scatter_add` has a maximum value of $2$ not $2+1=3$.

**Comment by thdai2000** [comment]
Ok, I just ran on my self-made dataset with a slightly different preprocessing so got this issue. It's my mistake. Thanks for your reply.
